language: scala

matrix:
  include:
    - scala: 2.12.3
      jdk: oraclejdk8
      env:
        - SBT_VERSION=1.0.1
# TODO test sbt 0.13.16/(2.12.3) vs 0.13.16(2.10.6) in matrix
    - scala: 2.12.3
      jdk: oraclejdk8
      env:
        - SBT_VERSION=0.13.16

before_install:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      openssl aes-256-cbc -K $encrypted_cf02a587d2be_key -iv $encrypted_cf02a587d2be_iv -in secring.gpg.enc -out secring.gpg -d;
    fi
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.2.3 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

script:
  - sbt ^^$SBT_VERSION clean compile test
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
      sbt ^^$SBT_VERSION scripted;
    fi

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      if grep -q "SNAPSHOT" version.sbt; then
        sbt ^^$SBT_VERSION publish;
      else
        if [ "$SBT_VERSION" = "1.0.1" ]; then
          sbt ^^$SBT_VERSION orgUpdateDocFiles;
          sbt ^^$SBT_VERSION depUpdateDependencyIssues;
          sbt ^^$SBT_VERSION release;
        fi
      fi
    fi
