language: scala
dist: trusty
jdk:
  - oraclejdk8
scala:
  - 2.12.9

before_install:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      openssl aes-256-cbc -K $encrypted_cf02a587d2be_key -iv $encrypted_cf02a587d2be_iv -in secring.gpg.enc -out secring.gpg -d;
    fi

install:
  - rvm use 2.6.5 --install --fuzzy
  - gem install jekyll -v 4

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile test
  - sbt ++$TRAVIS_SCALA_VERSION scripted;

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      if grep -q "SNAPSHOT" version.sbt; then
        sbt publish;
      else
        sbt orgUpdateDocFiles;
        git reset --hard HEAD;
        git clean -f;
        git checkout master;
        git pull origin master;
        sbt release;
        sbt docs/publishMicrosite;
      fi
    fi
