language: scala

scala:
- 2.10.6

before_install:
- export PATH=${PATH}:./vendor/bundle

install:
- gem install jekyll -v 2.5

script:
- sbt ++$TRAVIS_SCALA_VERSION publishLocal
- sbt ++$TRAVIS_SCALA_VERSION test scripted

after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then exit 0; fi
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash deploy.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "Not in master branch, skipping release"; fi
