name: sbt-microsites
baseurl: /sbt-microsites
description: An sbt plugin to create awesome microsites for your project
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.6.2
org: 47 Degrees
markdown: kramdown
